# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170619_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='missrequest',
            unique_together=set([('user', 'date')]),
        ),
    ]
