# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170701_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='findrequest',
            name='type',
            field=models.CharField(default='f', max_length=1),
        ),
        migrations.AddField(
            model_name='missrequest',
            name='type',
            field=models.CharField(default='m', max_length=1),
        ),
    ]
